=== nkandikattu/Hw5/XML/info_card.dtd
<?xml version = "1.0" encoding ="utf-8" ?>
<!-- info_card.dtd  -->
<!ELEMENT info_card (user+) >
<!ELEMENT user (name, address, quizResponses) >
<!ELEMENT name (first, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT quizResponses (question+) >
<!ELEMENT question (#PCDATA)>

=== nkandikattu/Hw5/XML/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE info_card SYSTEM "info_card.dtd" >
<info_card>
    <user>
        <name>
            <first>Susan</first>
            <last>Smith</last>
        </name>
        <address>susan.smith@gmail.com</address>
        <quizResponses>
            <question>Yes</question>
            <question>No</question>
            <question>Yes</question>
            <question>No</question>
            <question>Yes</question>
            <question>No</question>
            <question>Yes</question>
            <question>No</question>
            <question>Yes</question>
            <question>No</question>
        </quizResponses>
    </user>
    <user>
        <name>
            <first>James</first>
            <last>Johnson</last>
        </name>
        <address>jamesjohnson@yahoo.com</address>
        <quizResponses>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
            <question>Yes</question>
        </quizResponses>
    </user>
</info_card>
